version: "3.1"
services:
  nies:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/sport_scientists
    command: bash
    volumes:
      - $PWD:/workdir
  rstudio:
    image: rocker/verse:4
    ports:
      - "8787:8787"
    environment:
      PASSWORD: yourpassword
    volumes:
      - $PWD:/home/rstudio/workspace
